### ISSUE TITLE
Python DeprecationWarning for randrange()

### ISSUE THREAD

**Issue by zSprawl** [chazzu/hass-animated-scenes#25]
The new version of Python is throwing the following error with this addon. Hopefully it's an easy fix as this addon is a must have for the upcoming holiday season!

`/config/custom_components/animated_scenes/animations.py:297: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version return randrange(value[0], value[1], step) `

**Comment by chazzu** [comment]
This took me a little bit. The issue only affects users who specify a float in their configuration for an animation, and the only place that should be valid is in transition time. Since that was a previous feature request, I wanted to maintain the functionality but just casting them to int() would break it so that you can't specify fractions of a second for transition time anymore.
Anyway, v1.2.1 is being published now which will resolve the issue.
