### ISSUE TITLE
Animation lag with multiple lights

### ISSUE THREAD

**Issue by DarkTearStudios** [chazzu/hass-animated-scenes#33]
I kinda noticed this before I added more lights to my setup, but I've now added 8 more kasa bulbs for a total of 24. when i start the animation after a few seconds theres extreme lag, wont change in order, and some bulbs take a while to change. wasnt as big of an issue before I added the 8 more, still did it but took like 2 minutes or so before it started to lag. now its a few seconds. 
I really want to have some animaitons all over the house, but unless I just cant now. set to animate 1 light group that contains all 24 lights.

Any idea how to remedy this? I dont see it maxing the cpu or ram of the homeassistant

Thanks!

**Comment by DarkTearStudios** [comment]
Nevermind I'm pretty sure its a network load issue

**Comment by chazzu** [comment]
I've noticed the same, and I do think it's an issue with my Zigbee network lagging rather than the integration itself. Looking over the code, I kind of ran out of ideas for what I could do there to alleviate the problem. Each light is called asynchronously, and independently.

It DOES wait for Home Assistant to say each command has been 'sent' before it starts the next part. Suppose you have your wait time set to 3 seconds. It sends 24 commands, then waits for all 24 to be acknowledged by Home Assistant, THEN starts a timer for 3 seconds. If Home Assistant is a bit slow and takes, say, 5 seconds to complete sending the commands then the total time between animation frames would be 8 seconds and it would look awfully laggy.

However, I don't know that I can safely ignore this. I ran some testing on my local and the problem actually got worse when I didn't wait, as the Zigbee queue was filling up with unfinished/unsent commands.
