### ISSUE TITLE
Features Request - Sync lights and quick animation times

### ISSUE THREAD

**Issue by pmorange** [chazzu/hass-animated-scenes#6]
Hi,
Not really an issue, but some things that would be nice to have 👍 

- Animate all lights at once in sync. When I animate, each light has its animation, but I would like to animate all the lights in sync with the same brightness/color for all of them.
- Set animation times in milliseconds to allow for quick changes. 

Both above features would for instance allow to make an animation such as "blinking red lights" for an alarm.
All lights should blink white and red all at the same time, and they should do it quickier than they actually do (less than a second).

Cheers and thanks again for this !

**Comment by d8ahazard** [comment]
@chazzu - Regarding this one, it appears as if asyncio.sleep() already accepts a float parameter as it's input, meaning, it should be fairly simple to implement. The question is if you just change the change frequency value to be in ms, or add a second param "change_fequency_ms" or something that would then just get divided by 1000 to create the float to feed into the sleep call...

**Comment by chazzu** [comment]
For the first one, you can set the option "change_amount: all" to change all lights at the same time. I have added the change_sequence option. If you set this to 'true' it will change the lights in the order of the colors list rather than randomly.

I'll look into the miliseconds bit, but it might be a bit. I want to make a bigger change to allow light groups (see #1) and I think this will be part of it as well.

**Comment by Pieriot** [comment]
@d8ahazard tried changing the `asyncio.sleep(frequency)` to `asyncio.sleep(frequency/1000)`, and that works for ms, only problem is it seems like it queues up all the changes and won't switch scenes until all the changes are done. Any idea how to force stop the script?

**Comment by d8ahazard** [comment]
I'd have to look at the code a bit closer to know exactly how to implement
this, but I'd guess it's less about force-stopping the script, and ensuring
that each command to update the state isn't blocking, or that you're only
trying to send the next state once you're sure it's not trying to send the
previous state.

With asyncio, I see they have a Cancel Token feature, which could probably
be useful in this regard.

https://asyncio-cancel-token.readthedocs.io/en/latest/cancel_token.html

In my dotnet application, I do something similar, where I create a send
loop that is continuously sending data to my devices, and pass it a
Cancel(lation)Token. Inside the loop, I then do a while loop that checks if
the token is canceled (triggered in python), and then exit the loop at that
time. The color data I'm sending is then stored in a shared variable for
the class, which I populate with a separate method. This way, the color
generation is completely separate from the sending mechanism.

ALSO, inside my send loops, I ensure that every device being talked to is
in it's own try/catch so that if one device fails, it doesn't break the
whole thing. ;)

**Comment by chazzu** [comment]
When I made the big updates a while back, I allowed for a change frequency to be a float, allowing you to specify for example 0.05 seconds transition time.

Now, I've made a change that uses asyncio to do the lights asynchronously. In theory, you should get that near instantaneous transition you're looking for.

I did quite a bit of testing and while the effect was cool at first, it eventually stopped and the Sonoff adapter I was using burned out. Even after a system reboot, it failed to work for around 10 minutes. I would recommend caution.

**Comment by chazzu** [comment]
@d8ahazard Also, in the version I'm releasing now, I took your advice and threw the calls in try/except. Thanks for the idea!
